#version 450

#extension GL_EXT_buffer_reference : require

layout(local_size_x = 256) in;

struct Vertex {
  vec3 position;
  float uv_x;
  vec3 normal;
  float uv_y;
  vec4 color;
};

struct AABB {
  vec4 min;
  vec4 max;
};

struct Indices {
  int L;
  int R;
} indices;

layout(std430, binding = 0) writeonly buffer AABBOut {
  AABB aabbOut[];
};

layout(std430, buffer_reference) readonly buffer VertexBuffer {
  Vertex vertices[];
};

layout(push_constant) uniform Push {
  mat4 model;
  mat4 localTransform;
  VertexBuffer vertexBuffer;
} push;

void main() {
  AABB bboxOut;
  if (indices.L + 1 == indices.R) {}

  aabbOut[gl_GlobalInvocationID.x] = bboxOut;
}
