#version 450

#extension GL_EXT_buffer_reference : require

layout(local_size_x = 256) in;

struct Vertex {
  vec3 position;
  float uv_x;
  vec3 normal;
  float uv_y;
  vec4 color;
};

struct AABB {
  vec4 min;
  vec4 max;
};

layout(std430, binding = 0) writeonly buffer AABBOut {
  AABB aabbOut[];
};

layout(std430, buffer_reference) readonly buffer VertexBuffer {
  Vertex vertices[];
};

layout(push_constant) uniform Push {
  uint numPrimitives;
  VertexBuffer vertexBuffer;
} push;

AABB constructBBox(vec3 triangleVerts[3]) {
  vec3 min_vert = min(min(triangleVerts[0], triangleVerts[1]), triangleVerts[2]);
  vec3 max_vert = max(max(triangleVerts[0], triangleVerts[1]), triangleVerts[2]);
  AABB bbox;
  bbox.min = vec4(min_vert, 1.0);
  bbox.max = vec4(max_vert, 1.0);

  return bbox;
}

void main() {
  int x = int(gl_GlobalInvocationID.x / 3);
  int n = int(push.numPrimitives);
  if (x > n) return;

  Vertex vertex_1 = push.vertexBuffer.vertices[3 * x];
  Vertex vertex_2 = push.vertexBuffer.vertices[3 * x + 1];
  Vertex vertex_3 = push.vertexBuffer.vertices[3 * x + 2];

  vec3 location_1 = vertex_1.position;
  vec3 location_2 = vertex_2.position;
  vec3 location_3 = vertex_3.position;

  vec3 triangleVertices[3] = vec3[](location_1, location_2, location_3);

  AABB bboxOut = constructBBox(triangleVertices);
  aabbOut[x] = bboxOut;
}
